--- #YAML:1.0
name:               Business-OnlinePayment-Braintree
version:            0.0002
abstract:           Online payment processing through Briantree
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Business::OnlinePayment:  3.01
    Net::Braintree:       0.2
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
