---
abstract: 'Online payment processing through Braintree'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-Braintree
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: 3.01
  Net::Braintree: 0.02
  Test::More: 0
resources:
  bugtracker: https://github.com/interchange/Business-OnlinePayment-Braintree/issues
  repository: https://github.com/interchange/Business-OnlinePayment-Braintree
version: 0.006
